// Code generated by command: go run src.go -out ../../and_amd64.s -stubs ../../and_stubs_amd64.go -pkg and. DO NOT EDIT.

//go:build !purego

package and

// Sets dst to the bitwise and of a and b assuming all are 256*l bytes
//
//go:noescape
func andAVX2(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise or of a and b assuming all are 256*l bytes
//
//go:noescape
func orAVX2(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise and of not(a) and b assuming all are 256*l bytes
//
//go:noescape
func andNotAVX2(dst *byte, a *byte, b *byte, l uint64)

// Zero the return register
//
//go:noescape
func popcntAsm(a *byte, l uint64) int
