// Code generated by command: go run src.go -out ../and_amd64.s -stubs ../and_stubs_amd64.go -pkg and. DO NOT EDIT.

package and

// Sets dst to the bitwise and of a and b assuming all are 256*l bytes
//
//go:noescape
func andAVX2(dst *byte, a *byte, b *byte, l uint64)
