// Code generated by command: go run src.go -out ../../and_amd64.s -stubs ../../and_stubs_amd64.go -pkg and. DO NOT EDIT.

//go:build !purego

package and

// Sets dst to the bitwise and of a and b assuming all are 256*l bytes
//
//go:noescape
func andAVX2(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise and of a and b assuming all are 128*l bytes
//
//go:noescape
func andAVX(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise or of a and b assuming all are 256*l bytes
//
//go:noescape
func orAVX2(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise or of a and b assuming all are 128*l bytes
//
//go:noescape
func orAVX(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise xor of a and b assuming all are 256*l bytes
//
//go:noescape
func xorAVX2(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise xor of a and b assuming all are 128*l bytes
//
//go:noescape
func xorAVX(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise and of not(a) and b assuming all are 256*l bytes
//
//go:noescape
func andNotAVX2(dst *byte, a *byte, b *byte, l uint64)

// Sets dst to the bitwise and of not(a) and b assuming all are 128*l bytes
//
//go:noescape
func andNotAVX(dst *byte, a *byte, b *byte, l uint64)

// Bitwise inverts each byte of a into dst
//
//go:noescape
func notAVX2(dst *byte, a *byte, l uint64)

// Bitwise inverts each byte of a into dst
//
//go:noescape
func notAVX(dst *byte, a *byte, l uint64)

// Zero the return register
//
//go:noescape
func popcntAsm(a *byte, l uint64) int

// Sets each byte in dst to b
//
//go:noescape
func memsetAVX2(dst *byte, l uint64, b byte)

// Sets each byte in dst to b
//
//go:noescape
func memsetAVX(dst *byte, l uint64, b byte)
